spring.application.name=stock1

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://postgres-b59377ce-6b4a-4c24-860a-f89734e08973.cqryblsdrbcs.us-east-1.rds.amazonaws.com:7085/HTgJmifQZgOZ
spring.datasource.username=cad84456e6d3
spring.datasource.password=5554b4684a883fea
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional: Dialect for Hibernate (if using JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB


## JPA Configuration
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.redis.host=localhost
#spring.redis.port=6379
google.script.api.url=https://script.google.com/macros/s/AKfycbzkU2vCzcXGMbBVIT6Trlio5MWFTz3-aaZuOn57qPG07UiJK_p6f3Xr8HOkh41AJ43w/exec


#Redis
#spring.redis.host=master.rg-dfa92321-4535-4222-948d-5d7c2cb5e9ca.9u04ff.use1.cache.amazonaws.com
#spring.redis.port=1633
#spring.redis.password=XoRIVkhnTfpnOMUmOBWPVpdxzubGQHiq
#spring.redis.ssl.enabled=true
#spring.redis.timeout=60000
#spring.cache.type=redis
